### ISSUE TITLE
Push-To-Talk button stays pressed

### ISSUE THREAD

**Issue by sbruder** [acomminos/Plumble#121]
Hi,
If I press the Push-To-Talk-button, hold it and then rotate my device, Push-to-talk is still actictivated and I must press the PTT-Button again to deactivate Push-to-talk.
Thanks
Simon

**Comment by sbruder** [comment]
Note: I have a Samsung Galaxy Note with Android 4.4.4 and a Sony Xperia E1 with Android 4.4.2. The problem appears on both.

**Comment by acomminos** [comment]
Fixed in 82844d4.
