### ISSUE TITLE
Nightlies do use CPU while idle, 3.2.0 does not.

### ISSUE THREAD

**Issue by Natenom** [acomminos/Plumble#139]
# How do reproduce
* Start Plumble 3.2.0, connect to any server, press "Back" button to disconnect. Press "Home" or "Back" button to return to main screen of your Android.
* Repeat for Plumble Nightly
* Start OS monitor, sort by name and wait 5 minutes.

# What is the result?
* 3.2.0:
 * CPU-Time: 00:06
 * Status: always "Idle"
 * STime: 111
 * UTime: 530
 * Nice: 0
 * CPU-Usage: 0.0% always

* Nigthly:
 * CPU-Time: 00:17
 * Status: mostly "idle", sometimes "running" for few seconds.
 * STime: 561
 * UTime: 1222
 * Nice: 0
 * CPU-Usage: 1.3 - 2.x always

**Comment by acomminos** [comment]
Thanks for the report. I'd imagine that this is due to removing the suspension of the audio input thread when push to talk is not active; I'll reimplement this in the new input method abstraction.

**Comment by acomminos** [comment]
Fixed.
