### ISSUE TITLE
Import certificate as a file ?

### ISSUE THREAD

**Issue by Magador** [acomminos/Plumble#150]
I have a Nexus 5X running Android M 6.0.1, and this phone has no SD card slot in it. So, how can I transfer a .p12 certificate from a computer to this phone ?

**Comment by BuddyButterfly** [comment]
USB?

**Comment by Magador** [comment]
Sorry, I may have set a title which do not reflect exactly what is not possible.

How can you import a certificate into Plumble since #128 , because certificates are now stored into the database ?

**Comment by BuddyButterfly** [comment]
Should be no problem? Settings->Authentication->Import Certificate?

**Comment by Magador** [comment]
I do not have it, I do not have a Plumble directory in my phone either.
![screenshot_20160715-001528](https://cloud.githubusercontent.com/assets/6071537/16857656/95df014a-4a21-11e6-9a55-eacfe98cbb29.png)

**Comment by BuddyButterfly** [comment]
Did you try latest version #269? Then transfer your .p12 files to, for example, downloads dir and import from there.

**Comment by Magador** [comment]
Where should I get it ? I have version 3.2.0 on Google Play

**Comment by BuddyButterfly** [comment]
Search for plumble and jenkins. you will see the plumble nightly jenkins page. download latest apk and install.


Am 15. Juli 2016 01:49:11 MESZ, schrieb Jean-Baptiste Lenglet <notifications@github.com>:
>Where should I get it ? I have version 3.2.0 on Google Play
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/acomminos/Plumble/issues/150#issuecomment-232824657

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Magador** [comment]
Thanks you, I downloaded the 3.3.0-rc1 version from F-Droid, I see the option now.
