### ISSUE TITLE
Build file '/root/Plumble/app/build.gradle' line: 35

### ISSUE THREAD

**Issue by brizey02** [acomminos/Plumble#151]
$ sudo add-apt-repository ppa:cwchien/gradle

$ sudo apt-get update

$ sudo apt-get install gradle
ubuntu 14.04

FAILURE: Build failed with an exception.
- Where:
  Build file '/root/Plumble/app/build.gradle' line: 35
- What went wrong:
  A problem occurred evaluating project ':app'.
  
  > Could not read script '/root/Plumble/libraries/Leeroy-Gradle/leeroy.gradle' as it does not exist.

**Comment by acomminos** [comment]
Should be fixed now.
