### ISSUE TITLE
Solarized light link color same as bg

### ISSUE THREAD

**Issue by svbeon** [acomminos/Plumble#154]
![img_20160808_115418](https://cloud.githubusercontent.com/assets/10356719/17476169/e9622734-5d5e-11e6-977b-c334d9de2bb4.jpg)
In this image there is a link sent, the issue is that the link's color matches the bg - both for own and others messages

**Comment by acomminos** [comment]
Fixed in 127a9942f3b9bfa006d380d3a6163b7cc076f581, thanks.
