### ISSUE TITLE
Admin permissions (in user panel) sometimes not available to admin user

### ISSUE THREAD

**Issue by Natenom** [acomminos/Plumble#43]
Can't reproduce it but sometimes one has no admin permissions on a server. To fix it one needs to enter the root channel once.

**Comment by acomminos** [comment]
Should be fixed in 28dca8ede295a2e801b0c59f1187e6fc8bca81ca, please reopen if you're still having this issue.

**Comment by Natenom** [comment]
I am sorry, but it is not fixed in 244. But the behaviour is changed a bit. Sometimes you have admin permissions, sometimes not and sometimes you see the admin permissions for a very short time period (< sec) and then they disappear and you can only see the normal context menu.
